
services:
  api:
    build: .
    ports:
      - "8081:8081"  # API доступен на 8081
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"  # Nginx слушает 8080 и проксирует на api:8081
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
    external: true