// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AddParticipant struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}

type Board struct {
	ID    string  `json:"id"`
	Title string  `json:"title"`
	Tasks []*Task `json:"tasks"`
}

type ChangeBoard struct {
	ID      string `json:"id"`
	BoardID string `json:"boardId"`
}

type Comment struct {
	ID          string `json:"id"`
	TaskID      string `json:"taskId"`
	AuthorID    string `json:"authorId"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewBoard struct {
	ProjectID string `json:"projectId"`
	Title     string `json:"title"`
}

type NewComment struct {
	TaskID      string `json:"taskId"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type NewProject struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

type NewTask struct {
	Title       string    `json:"title"`
	BoardID     string    `json:"boardId"`
	Description string    `json:"description"`
	Deadline    time.Time `json:"deadline"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Project struct {
	ID             string    `json:"id"`
	AuthorID       string    `json:"authorId"`
	ParticipantsID []string  `json:"participantsId"`
	Title          string    `json:"title"`
	Description    string    `json:"description"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type Query struct {
}

type Subscription struct {
}

type Task struct {
	ID          string    `json:"id"`
	BoardID     string    `json:"boardId"`
	AuthorID    string    `json:"authorId"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Deadline    time.Time `json:"deadline"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Tokens struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type UpdateTask struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Deadline    time.Time `json:"deadline"`
}

type User struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Username string `json:"username"`
}
