services:
  postgresql-ya:
    image: postgres:17
    env_file: ./config/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 102104
      POSTGRES_DB: scrum
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  auth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      postgresql-ya:
        condition: service_healthy
    env_file:
      - ./config/.env
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    external: true
